### ISSUE TITLE
VEG Episode 13

### ISSUE THREAD

**Issue by liggieep** [nedragrevev/custom-subs#3] opened 2021-02-10 23:34 UTC
Violet Evergarden (regular subs, not signs and songs) are having timing issues on my end, whereas all the other episodes are fine, at least with the BD rip I use. first few lines of the episode are timed fine, and then violet's "Thank you" comes to early, and every subsequent line comes increasingly earlier. My rip of the episode is 26m51s, with the final line spoken at 26m43s, whereas yours are set at 23m34s. Not sure if there is some NTCS versus PAL thing going on here, but I've grabbed multiple different rips of the show and they all appear to be 26m51s for episode 13. Any idea what is going on?

**Comment by liggieep** [comment] 2021-02-10 23:35
i really like your subs and want to keep them all, but I'm not sure how to fix this without re-timing it myself

**Comment by nedragrevev** [comment] 2021-02-11 02:17
The US Funimation release must be including the extended version of episode 13, whereas my AU release only includes the standard version. I understand the JP Blu-rays also include the extended version. I just checked Netflix, and as you'd expect, they just stream the standard version as well which is what Asenshi based their subs on.

I just had a look at some extended version subs and in terms of using my subs, unfortunately they include additional dialogue which means my subs won't work even with some simple time shift of the out of sync lines (a full retime is unnecessary). I think there's a few additional scenes, some dialogue free, but at least one with additional dialogue (after Violet writes the letter for the man who lost his son, just before the air show). The other difference which accounts for the few extra minutes is the ED song. In the standard version it's omitted, but it's included in the extended.

Sorry, I'd like to help but I don't own the extended version release so I'm not going to be able to.

**Comment by nedragrevev** [comment] 2021-02-11 02:49
I'll close this for now, since it's not a bug, just a difference in release. To be honest I'd really like to help, but I don't sub anything I don't own. Sorry.

**Closed by nedragrevev** 2021-02-11 02:49 UTC
